- name: Setup NodeJs repo
  shell: curl -sL https://rpm.nodesource.com/setup_16.x | bash -


- name: Install dependencies
  ansible.builtin.yum:
    name:
      - unzip
      - nodejs
    state: present

- name: Application User Setup and Download App Files
  import_tasks: add-user.yml

- name:  Copy {{COMPONENT}} filebeat and rsyslog config
  template: src={{ item.src }} dest={{ item.dest }}
  loop:
    - { src: 'systemd.service' , dest: '/etc/systemd/system/{{COMPONENT}}.service' }
    - { src: 'rsyslog.conf' , dest: '/etc/rsyslog.d/{{COMPONENT}}.conf' }

- name: Start {{COMPONENT}} Service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  notify: restart Service