- name: Create a jenkins multibranch job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/test.xml') }}"
    name: test
    password: "@123Chaitu"
    url: http://34.224.223.136:8080
    user: admin

- name: Create a jenkins multibranch job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/mbranch.xml') }}"
    name: test
    password: "@123Chaitu"
    url: http://34.224.223.136:8080
    user: admin